GET http://localhost:8000/products/ HTTP/1.1

###

POST http://localhost:8000/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzgwNDEzMzM3LCJpYXQiOjE3ODA0MTMwMzcsImp0aSI6IjZmMmQxODA2ZGI4NDQ2M2U5MWU1NzYxYWQyZTJmMDZhIiwidXNlcl9pZCI6IjEifQ.8XSq_I-cFtpb406DtFTkLUgv0xsmlgdi0kppFQF_ffI

{
    "name": "panela",
    "price": 300.00,
    "description": "A good panela",
    "stock": 8
}


###
GET http://localhost:8000/products/3/ HTTP/1.1

###
PUT  http://localhost:8000/products/3/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzgwNDIyOTg3LCJpYXQiOjE3ODA0MjI2ODcsImp0aSI6IjRkZmEzMGJlNmEzZTRlNWM5MGJhNTU1NTdiN2RmNjljIiwidXNlcl9pZCI6IjEifQ.wDzrgjuwgAB4iox5gL7xzkZALD17GGgc9eCWIVq5dao

{
    "name": "panela",
    "price": 300.00,
    "description": "A good panela",
    "stock": 8
}

###
DELETE http://localhost:8000/products/3/ HTTP/1.1


###
POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "test"
}


###
GET http://localhost:8000/user-orders/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzgwNDExNzY4LCJpYXQiOjE3ODA0MTE0NjgsImp0aSI6IjcxYTkzYzVhODI1YzRlY2RhZTEyNzZmYjVkNzEzOGZkIiwidXNlcl9pZCI6IjEifQ.nmtSSO8NtFXUPf4L54HnZtBCHxlAJAPhrrHggAAGGP0

###
POST http://localhost:8000/api/token/refresh/ HTTP/1.1
Content-Type: application/json

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4MDQ5OTQwNiwiaWF0IjoxNzgwNDEzMDA2LCJqdGkiOiJhMTIxOTNlMzhmYjU0ZjYzOTEzNTZlYWRmZWI3N2U2ZCIsInVzZXJfaWQiOiIxIn0.nQDBvPsw-4ZYMKTVeFbFUV5LJfFjJ7PZK1BDpD3JwtM"
}

###

GET http://localhost:8000/orders/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzgxMDMwNTYwLCJpYXQiOjE3ODEwMzAyNjAsImp0aSI6IjY2ZGJlZTAxY2RkMDRiNmE4Mjg5MjI1NGUyOGE2YTM5IiwidXNlcl9pZCI6IjEifQ.yl5_FeT5xONWRLBiJ-LZMSETJH8Qfe92ZAp7YTlDEHw

###

GET http://localhost:8000/orders/b0fbb7b7-e16b-481d-b101-891d5f11ad45 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzgxMDMwNTYwLCJpYXQiOjE3ODEwMzAyNjAsImp0aSI6IjY2ZGJlZTAxY2RkMDRiNmE4Mjg5MjI1NGUyOGE2YTM5IiwidXNlcl9pZCI6IjEifQ.yl5_FeT5xONWRLBiJ-LZMSETJH8Qfe92ZAp7YTlDEHw


###

POST http://localhost:8000/orders/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzgxMDMzOTUzLCJpYXQiOjE3ODEwMzM2NTMsImp0aSI6IjJkZjE5MTNmZjdmZTQ0ZGU5Mjk0ZWU5NmQ0MjIyYjEzIiwidXNlcl9pZCI6IjEifQ.imTSFJ4YWYsr95zN3kFNzWusFaP1i9p716bM0Gp0IyE

{
    "status": "Pending",
    "items": [
        {
            "product": 5,
            "quantity": 2
        },
        {
            "product": 3,
            "quantity": 1
        }
    ]
}