GET http://localhost:8000/products/ HTTP/1.1

###

POST http://localhost:8000/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzgwNDEzMzM3LCJpYXQiOjE3ODA0MTMwMzcsImp0aSI6IjZmMmQxODA2ZGI4NDQ2M2U5MWU1NzYxYWQyZTJmMDZhIiwidXNlcl9pZCI6IjEifQ.8XSq_I-cFtpb406DtFTkLUgv0xsmlgdi0kppFQF_ffI

{
    "name": "panela",
    "price": 300.00,
    "description": "A good panela",
    "stock": 8
}


###
GET http://localhost:8000/products/3/ HTTP/1.1

###
PUT  http://localhost:8000/products/3/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzgwNDIyOTg3LCJpYXQiOjE3ODA0MjI2ODcsImp0aSI6IjRkZmEzMGJlNmEzZTRlNWM5MGJhNTU1NTdiN2RmNjljIiwidXNlcl9pZCI6IjEifQ.wDzrgjuwgAB4iox5gL7xzkZALD17GGgc9eCWIVq5dao

{
    "name": "panela",
    "price": 300.00,
    "description": "A good panela",
    "stock": 8
}

###
DELETE http://localhost:8000/products/3/ HTTP/1.1


###
POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "test"
}


###
GET http://localhost:8000/user-orders/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzgwNDExNzY4LCJpYXQiOjE3ODA0MTE0NjgsImp0aSI6IjcxYTkzYzVhODI1YzRlY2RhZTEyNzZmYjVkNzEzOGZkIiwidXNlcl9pZCI6IjEifQ.nmtSSO8NtFXUPf4L54HnZtBCHxlAJAPhrrHggAAGGP0

###
POST http://localhost:8000/api/token/refresh/ HTTP/1.1
Content-Type: application/json

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4MDQ5OTQwNiwiaWF0IjoxNzgwNDEzMDA2LCJqdGkiOiJhMTIxOTNlMzhmYjU0ZjYzOTEzNTZlYWRmZWI3N2U2ZCIsInVzZXJfaWQiOiIxIn0.nQDBvPsw-4ZYMKTVeFbFUV5LJfFjJ7PZK1BDpD3JwtM"
}

###

GET http://localhost:8000/orders/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzgxMDMwNTYwLCJpYXQiOjE3ODEwMzAyNjAsImp0aSI6IjY2ZGJlZTAxY2RkMDRiNmE4Mjg5MjI1NGUyOGE2YTM5IiwidXNlcl9pZCI6IjEifQ.yl5_FeT5xONWRLBiJ-LZMSETJH8Qfe92ZAp7YTlDEHw

###

GET http://localhost:8000/orders/b0fbb7b7-e16b-481d-b101-891d5f11ad45 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzgxMDQ5MzI3LCJpYXQiOjE3ODEwNDkwMjcsImp0aSI6Ijk2Yzk0YTRhYWJmMDRkNjlhMWNhOTkyYjVkNzMzYjMzIiwidXNlcl9pZCI6IjEifQ.ASkbZlvsvqI7tehJu-VYjyCkSHm-JmWGTXOtyzZrcWo

###

PUT  http://localhost:8000/orders/8ca95da0-cf09-4066-83ba-88f8976bd788/  HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzgxMDQ5ODkzLCJpYXQiOjE3ODEwNDk1OTMsImp0aSI6IjNkMGJjZjVhMDJhYjQyZmJiMTZkYzYxYzZiYmQ1YmJiIiwidXNlcl9pZCI6IjEifQ.TiP4ubGO4fCHqqhVCx7enTt2Ddo3W13yVlw11Fb3Sr4

{
    "status": "Confirmed",
    "items": [
        {
            "product": 5,
            "quantity": 4
        },
        {
            "product": 3,
            "quantity": 3
        }
    ]
}


###
DELETE  http://localhost:8000/orders/8ca95da0-cf09-4066-83ba-88f8976bd788/  HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzgxMDQ5ODkzLCJpYXQiOjE3ODEwNDk1OTMsImp0aSI6IjNkMGJjZjVhMDJhYjQyZmJiMTZkYzYxYzZiYmQ1YmJiIiwidXNlcl9pZCI6IjEifQ.TiP4ubGO4fCHqqhVCx7enTt2Ddo3W13yVlw11Fb3Sr4


###

POST http://localhost:8000/orders/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzgxMDQ5ODkzLCJpYXQiOjE3ODEwNDk1OTMsImp0aSI6IjNkMGJjZjVhMDJhYjQyZmJiMTZkYzYxYzZiYmQ1YmJiIiwidXNlcl9pZCI6IjEifQ.TiP4ubGO4fCHqqhVCx7enTt2Ddo3W13yVlw11Fb3Sr4

{
    "status": "Pending",
    "items": [
        {
            "product": 5,
            "quantity": 2
        },
        {
            "product": 3,
            "quantity": 1
        }
    ]
}